CREATE TABLE IF NOT EXISTS items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    fragile BOOLEAN NOT NULL,
    width FLOAT NOT NULL,
    height FLOAT NOT NULL,
    depth FLOAT NOT NULL,
    weight FLOAT NOT NULL,
    quantity INTEGER NOT NULL CHECK (quantity >= 0),
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);

CREATE TABLE IF NOT EXISTS reserves (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    cart_id UUID NOT NULL,
    product_id UUID NOT NULL,
    reserved_quantity INTEGER NOT NULL CHECK (reserved_quantity >= 0)
);